### ISSUE TITLE
i have problem with uninstall system please help me

### ISSUE THREAD

**Issue by SunryTeang** [Chrisplus/RootManager#6]
my code below:
 class UninstallSystemApp(var mContext: Context) : AsyncTask<Void, Void, Result?>() {
        val appPackage = "a855solution.gais.app"
        override fun doInBackground(vararg p0: Void?): Result? {
            return RootManager.getInstance().uninstallSystemApp(AppManager.getAppApkPathInstalled(mContext, appPackage))
        }

        override fun onPreExecute() {
            println("Uninstalling package  $appPackage .")
            super.onPreExecute()
        }

        override fun onPostExecute(result: Result?) {
            println("Uninstall $appPackage ${result?.result} with the message  ${result?.message}")
            super.onPostExecute(result)
        }
    }
===================================
error:
D/RootManager::Shell: Starting shell: su
D/RootManager::Shell: Starting shell: su
D/RootManager::Shell: Starting shell: su
D/RootManager::Shell: Starting shell: su
D/RootManager::Shell: Starting shell: su
D/RootManager: Could not start shell
W/System.err: java.io.IOException: Error running exec(). Command: [su] Working Directory: null Environment: null
W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:211)
W/System.err:     at java.lang.Runtime.exec(Runtime.java:173)
W/System.err:     at java.lang.Runtime.exec(Runtime.java:246)
W/System.err:     at java.lang.Runtime.exec(Runtime.java:189)
W/System.err:     at com.chrisplus.rootmanager.container.Shell.<init>(Shell.java:75)
W/System.err:     at com.chrisplus.rootmanager.container.Shell.startRootShell(Shell.java:135)
W/System.err:     at com.chrisplus.rootmanager.container.Shell.startRootShell(Shell.java:121)
W/System.err:     at com.chrisplus.rootmanager.utils.Remounter.remount(Remounter.java:93)
W/System.err:     at com.chrisplus.rootmanager.RootManager.remount(RootManager.java:375)
W/System.err:     at com.chrisplus.rootmanager.RootManager.uninstallSystemApp(RootManager.java:283)
W/System.err:     at biz.mobileone.posmanagment.dashboard.MainActivity$someTask.doInBackground(MainActivity.kt:121)
W/System.err:     at biz.mobileone.posmanagment.dashboard.MainActivity$someTask.doInBackground(MainActivity.kt:118)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:288)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: java.io.IOException: Permission denied
W/System.err:     at java.lang.ProcessManager.exec(Native Method)
W/System.err:     at java.lang.ProcessManager.exec(ProcessManager.java:209)
W/System.err: 	... 17 more
D/RootManager: Status Code is 409
I/System.out: Uninstall a855solution.gais.app false with the message  Illegal Parameters or State
===============

**Comment by Chrisplus** [comment]
Hi,

I'm not sure which model you are using and if your phone is rooted. But from the log,

``
Error running exec(). Command: [su] Working Directory: null Environment: null
``

It seems rootmanager cannot find SU for further steps.

**Comment by SunryTeang** [comment]
@Chrisplus Thank you
